### ISSUE TITLE
add pagination for the dataset-urls endpoint

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#154]
Followup to #149 

One approach mentioned by @jwodder is to add in response header "link" field pointing to the end point for the next listing.  But then tricky how to provide total number of such "pages". This is how GitHub RestAPI does it.

An alternative is to change return structure to provide e.g.

```json
{
"count": 280,
  "next": "https://api.dandiarchive.org/api/dandisets/?draft=true&embargoed=true&empty=true&page=2",
  "previous": null,
  "results": [
...
]
}
```

is what we return in DANDI API, see/try https://api.dandiarchive.org/swagger/ .

**Comment by jwodder** [comment]
GitHub documents how pagination works in its REST API at <https://docs.github.com/en/rest/guides/using-pagination-in-the-rest-api?apiVersion=2022-11-28>.  Note that, while most paginated GitHub API endpoints return arrays of objects, all the paginated endpoints that have been added in the last four years or so are instead of the form:

```json
{
  "total_count": 809,
  "workflow_runs": [
    ...
  ]
}
```

which lets the requestor know how many items in total there are across all pages.

I do feel like mentioning that I've used many REST APIs over the years, and GitHub's is the only one that uses Link headers for pagination instead of putting the links in the body of the response like Dandi Archive does.

**Comment by candleindark** [comment]
> GitHub documents how pagination works in its REST API at https://docs.github.com/en/rest/guides/using-pagination-in-the-rest-api?apiVersion=2022-11-28. Note that, while most paginated GitHub API endpoints return arrays of objects, all the paginated endpoints that have been added in the last four years or so instead return responses of the form:
> 
> ```json
> {
>   "total_count": 809,
>   "workflow_runs": [
>     ...
>   ]
> }
> ```
> 
> which lets the requestor know how many items in total there are across all pages.
> 
> I do feel like mentioning that I've used many REST APIs over the years, and GitHub's is the only one that uses Link headers for pagination instead of putting the links in the body of the response like Dandi Archive does.

Thanks. This is very useful.

**Comment by candleindark** [comment]
@yarikoptic Is it right to say that this feature should be accompanied by the feature of sorting by different parameters, such as last update time or number annexed files in working tree.

**Comment by yarikoptic** [comment]
likely indeed worth making it all out in one shot while at it since it would help with making a web UI to just use API to display them later.

**Comment by candleindark** [comment]
I think it is even necessary to do so since with pagination a client will only get a portion of all the results a time, and it has to rely on the server to do any kind of sorting of all the results.
