### ISSUE TITLE
Return back functionality to trigger an update for a URL

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#198]
In the old API PATCHing for a dataset request would trigger either registration or an update for the dataset.  ATM we do only registration for a new but refuse to do anything in case we already know that URL.  We should make it possible for a user to just report a URL which might be known to us or not. So let's adjust POST so if it finds a URL known, it would just schedule it to be updated.

**Comment by yarikoptic** [comment]
see the code of few lines in https://github.com/datalad/datalad-registry/issues/112#issuecomment-1610067233 on how to "schedule" an update

**Comment by yarikoptic** [comment]
with https://github.com/datalad/datalad-registry/pull/201 in mind where we changed json record schema for the `branches`, we would need a way to trigger update even if it is not due -- so if `force` then for `check_url` it should trigger update of the record even if there is no updates in the repo

**Comment by candleindark** [comment]
I am a bit confused. Please confirm or correct my current understanding:

Re-POSTing an existing URL will trigger a possible update of the repo in the `cache` in our system by doing some kind of "fetch" in the clone in the cache. If the repo is updated through this "fetch" operation (update in any of the remote branches), all possible changed info, including metadata, related to this dataset in the database will be updated. Otherwise, I assume, nothing in the database need to be updated.

**Comment by candleindark** [comment]
#204 closes this issue.
