### ISSUE TITLE
celery (flower?) is "too busy" doing nothing/not much

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-registry#258]
Looking at typhon ATM it seems that celery processes are consuming considerable amount of CPU time but actually seems to be doing nothing useful since I don't see them spawning any underlying processes etc. I could be wrong, and it could be all Python-space metadata extraction I guess but it seems to be primarily the monitoring service (flower).  Worth researching into what it is doing.  Might be worth checking with `py-spy top` on what it actually is busy with etc.

**Comment by candleindark** [comment]
A [request](https://github.com/mher/flower/issues/771#issuecomment-1866943813) has been made the Flower team.

**Comment by candleindark** [comment]
FTR: The CPU usage by Flower, the Celery monitor service, has been somewhat reduced after https://github.com/datalad/datalad-registry/pull/281 and https://github.com/datalad/datalad-registry/pull/284 (my bet is on https://github.com/datalad/datalad-registry/pull/281 being the actual cause for the reduction). As it stands now, with max of 100,000 most recent task records, the AVE CPU usage is ≈66% instead of 85%+.

![Screenshot 2024-01-31 at 10 34 39 AM](https://github.com/datalad/datalad-registry/assets/12135617/8c4ff91e-14a1-4305-bd56-652d3484392b)
